import { createContext, useContext, useState, useCallback } from 'react';

const LS_KEY = 'floradesigner_language';

const translations = {
  ka: {
    // Nav
    'nav.home': 'მთავარი',
    'nav.shop': 'მაღაზია',
    'nav.ai': 'AI დიზაინი',
    'nav.about': 'ჩვენ შესახებ',
    'nav.contact': 'კონტაქტი',
    'nav.orders': 'შეკვეთები',
    'nav.cart': 'კალათა',
    // Common filter values
    'All': 'ყველა',
    'In Stock': 'მარაგშია',
    'Unavailable': 'არ არის მარაგში',
    'Out of Stock': 'არ არის მარაგში',
    'Any Price': 'ნებისმიერი ფასი',
    'Under ₾80': '₾80-ამდე',
    '₾80 - ₾120': '₾80 – ₾120',
    '₾120 - ₾160': '₾120 – ₾160',
    'Over ₾160': '₾160-ზე მეტი',
    // Order type / status labels
    'Ready-made': 'მზა',
    'AI-generated': 'AI-გენერირებული',
    'Mixed': 'შერეული',
    'Pending': 'მოლოდინი',
    'Preparing': 'მზადება',
    'Out for Delivery': 'მიდის',
    'Delivered': 'მიტანილია',
    'Cancelled': 'გაუქმებული',
    // Payment labels
    'pay.cash': 'ნაღდი მიტანისას',
    'pay.cash.desc': 'გადაიხადეთ მაშინ, როდესაც თაიგული კართან მოვა.',
    'pay.card': 'სადემო ბარათი',
    'pay.card.desc': 'სიმულირებული ბარათის გადახდა – რეალური ტრანზაქცია არ ხდება.',
    'pay.bank': 'საბანკო გადარიცხვა',
    'pay.bank.desc': 'სიმულირებული გადარიცხვა სადემო მიზნებისთვის.',
    // Home
    'home.tag': '',
    'home.title1': '',
    'home.title2': '',
    'home.desc': 'გადახედეთ ჩვენს ხელნაკეთ კოლექციას ან ნება მიეცით AI-ს შექმნას სასურველი თაიგული – თქვენი სურვილის და გემოვნების მიხედვით.',
    'home.browse': 'თაიგულების დათვალიერება',
    'home.tryai': 'სცადე AI დიზაინი',
    'home.featured': 'რჩეული კომპოზიციები',
    'home.viewall': 'ყველა თაიგულის ნახვა →',
    'home.how.title': 'როგორ მუშაობს AI დიზაინი',
    'home.how.desc': 'თაიგულის შეკვეთა არასდროს ყოფილა ასე მარტივი. უბრალოდ აღწერეთ თქვენთვის სასურველი თაიგული, დანარჩენზე კი AI და გამოცდილი დიზაინერები იზრუნებენ.',
    'home.step1.title': 'აღწერეთ თქვენი სურვილი',
    'home.step1.desc': 'გვიამბეთ შემთხვევის, სასურველი ფერების, ყვავილებისა და სხვა სურვილების შესახებ.',
    'home.step2.title': 'AI ქმნის თაიგულს',
    'home.step2.desc': 'ჩვენი AI მყისიერად ქმნის სპეციალურ თაიგულს თქვენი აღწერის, სტილისა და ბიუჯეტის მიხედვით.',
    'home.step3.title': 'გადახედეთ და მოარგეთ',
    'home.step3.desc': 'გადახედეთ AI-ის შეთავაზებებს, შეცვალეთ დეტალები ან ახლოს მდგომი სტილი ჩვენი კატალოგიდან.',
    'home.step4.title': 'შეიძინეთ და მიიღეთ',
    'home.step4.desc': 'განათავსეთ შეკვეთა და სუფრეში ყვავილები კართან მოგეწოდებათ.',
    'home.why.title': 'რატომ FloraDesigner?',
    'home.why.desc': 'ჩვენ ვაერთიანებთ ოსტატური მეყვავილეობის სითბოსა და თანამედროვე ტექნოლოგიების სიზუსტეს.',
    'home.ben1.title': 'გამოცდილი დიზაინერები',
    'home.ben1.desc': 'კატალოგის თითოეული თაიგული პროფესიონალი მეყვავილეების მიერ არის შერჩეული.',
    'home.ben2.title': 'ხარისხი',
    'home.ben2.desc': 'ვყიდულობთ პირდაპირ ადგილობრივი მწარმოებლებისგან, რათა ყვავილები პიკ სიახლეში ჩამოვიდეს.',
    'home.ben3.title': 'AI-ს დახმარება',
    'home.ben3.desc': 'ვერ პოულობთ სასურველ თაიგულს? ნება მიეცით AI-ს შექმნას ინდივიდუალურად.',
    'home.ben4.title': '100% კმაყოფილება',
    'home.ben4.desc': 'თუ თაიგული მოლოდინს ვერ გამართლებს, შევცვლით ან დაგიბრუნებთ ფულს.',
    'home.cta.title': 'მზად ხართ სასურველი თაიგულის მოსაძებნად?',
    'home.cta.desc': 'გადახედეთ ხელნაკეთ კომპოზიციებს ან AI დაგეხმარებათ.',
    'home.cta.shop': 'შეიძინე ახლა',
    'home.cta.ai': 'AI დიზაინი',
    // Products
    'products.title': 'ჩვენი თაიგულები',
    'products.subtitle': 'გადახედეთ ჩვენი ხელნაკეთი ყვავილების სრულ კოლექციას.',
    'products.fallback': 'გამოიყენება სადემო მონაცემები, რადგან სერვერი მიუწვდომელია.',
    'products.search': 'ძებნა სახელით ან აღწერით...',
    'products.filter.category': 'კატეგორია',
    'products.filter.color': 'ფერი',
    'products.filter.flower': 'ყვავილი',
    'products.filter.size': 'ზომა',
    'products.filter.occasion': 'შემთხვევა',
    'products.filter.price': 'ფასის დიაპაზონი',
    'products.instock.label': 'მხოლოდ მარაგში',
    'products.clearall': 'ყველა ფილტრის გასუფთავება',
    'products.loading': 'იტვირთება...',
    'products.showing': 'ნაჩვენებია {count} {total}-დან',
    'products.nomatch': 'ფილტრებით თაიგული ვერ მოიძებნა.',
    'products.clearfilters': 'ფილტრების გასუფთავება',
    'products.viewdetails': 'დეტალები',
    'products.addtocart': 'კალათაში',
    'products.added': 'დაემატა!',
    // ProductDetails
    'details.back': '← უკან',
    'details.loading': 'იტვირთება...',
    'details.notfound.title': 'თაიგული ვერ მოიძებნა',
    'details.notfound.desc': 'ამ ID-ის მქონე თაიგული ვერ მოიძებნა. შეიძლება წაშლილი ან ბმული არასწორია.',
    'details.notfound.btn': 'ყველა თაიგულთან დაბრუნება',
    'details.flowers': 'ყვავილები',
    'details.colors': 'ფერები',
    'details.size': 'ზომა',
    'details.occasion': 'შემთხვევა',
    'details.availability': 'ხელმისაწვდომობა',
    'details.delivery': 'მიტანა',
    'details.instock': 'მარაგშია',
    'details.outofstock': 'ამჟამად მიუწვდომელია',
    'details.arrangement': 'კომპოზიცია',
    'details.idealfor': 'შესაფერისია',
    'details.qty': 'რაოდენობა',
    'details.addtocart': 'კალათაში დამატება',
    'details.added': 'კალათაში დაემატა! —',
    'details.viewcart': 'კალათის ნახვა',
    'details.addedlabel': 'კალათაში დაემატა!',
    'details.outofstock.msg': 'ეს თაიგული ამჟამად არ არის მარაგში. მოიცადეთ ან გადახედეთ მსგავს კომპოზიციებს.',
    'details.related': 'შეიძლება ასევე მოგეწონოთ',
    // Cart
    'cart.title': 'თქვენი კალათა',
    'cart.empty.text': 'კალათა ცარიელია.',
    'cart.empty.btn': 'თაიგულების დათვალიერება',
    'cart.clear': 'კალათის გასუფთავება',
    'cart.summary': 'შეკვეთის შეჯამება',
    'cart.total': 'სულ',
    'cart.shipping': 'მიტანა გამოითვლება გადახდისას',
    'cart.checkout': 'გადახდაზე გადასვლა',
    'cart.continueshop': 'შოპინგის გაგრძელება',
    'cart.each': 'ერთი',
    'cart.item.ai': 'AI-გენერირებული',
    'cart.item.ready': 'მზა',
    'cart.item.custom': 'სპეციალური',
    // Checkout
    'checkout.title': 'გადახდა',
    'checkout.subtitle': 'შეავსეთ მიტანის დეტალები შეკვეთის განსათავსებლად.',
    'checkout.empty.text': 'კალათა ცარიელია. დაამატეთ თაიგულები გადახდამდე.',
    'checkout.empty.btn': 'თაიგულების დათვალიერება',
    'checkout.delivery.title': 'მიტანის დეტალები',
    'checkout.name': 'სრული სახელი',
    'checkout.phone': 'ტელეფონის ნომერი',
    'checkout.address': 'მიტანის მისამართი',
    'checkout.date': 'მიტანის თარიღი',
    'checkout.timeslot': 'დრო',
    'checkout.note': 'შენიშვნა მეყვავილეებისთვის',
    'checkout.note.optional': '(სურვილისამებრ)',
    'checkout.note.placeholder': 'ბარათის ტექსტი, სპეციალური თხოვნები...',
    'checkout.payment.title': 'გადახდის მეთოდი',
    'checkout.payment.note': 'ეს სადემო მაღაზიაა – რეალური გადახდები არ ხდება.',
    'checkout.submit': 'შეკვეთის განთავსება',
    'checkout.placing': 'შეკვეთა...',
    'checkout.back': 'კალათაში დაბრუნება',
    'checkout.summary': 'შეკვეთის შეჯამება',
    'checkout.qty': 'რაოდ.',
    'checkout.subtotal': 'ჯამი',
    'checkout.delivery.free': 'მიტანა',
    'checkout.free': 'უფასო',
    'checkout.total': 'სულ',
    'checkout.time.select': 'დროის ინტერვალის შეარჩევა',
    'err.name': 'სრული სახელი სავალდებულოა.',
    'err.phone': 'ტელეფონის ნომერი სავალდებულოა.',
    'err.address': 'მიტანის მისამართი სავალდებულოა.',
    'err.date': 'მიტანის თარიღი სავალდებულოა.',
    'err.time': 'გთხოვთ, მიუთითოთ დროის ინტერვალი.',
    'err.payment': 'გთხოვთ, შეარჩიოთ გადახდის მეთოდი.',
    // OrderSuccess
    'success.nofound.text': 'ბოლო შეკვეთა ვერ მოიძებნა. დაიწყეთ შოპინგი.',
    'success.nofound.btn1': 'თაიგულების დათვალიერება',
    'success.nofound.btn2': 'მთავარ გვერდზე',
    'success.title': 'შეკვეთა განთავსებულია!',
    'success.desc': 'გმადლობთ, {name}. თქვენი შეკვეთა მიღებულია და მოვამზადებთ მიტანისთვის.',
    'success.backend': 'შეკვეთა შენახულია მონაცემთა ბაზაში.',
    'success.local': 'სადემო შეკვეთა შენახულია ლოკალურად (სერვერი მიუწვდომელი იყო).',
    'success.details': 'შეკვეთის დეტალები',
    'success.orderid': 'შეკვეთის ID',
    'success.customer': 'მომხმარებელი',
    'success.phone': 'ტელეფონი',
    'success.deliveryto': 'მიტანა',
    'success.deliverydate': 'მიტანის თარიღი',
    'success.timeslot': 'დრო',
    'success.payment': 'გადახდა',
    'success.note': 'შენიშვნა',
    'success.items': 'შეძენილი ნივთები',
    'success.total': 'სულ',
    'success.continue': 'შოპინგის გაგრძელება',
    'success.vieworders': 'ჩემი შეკვეთები',
    // OrderHistory
    'history.title': 'ჩემი შეკვეთები',
    'history.loading': 'შეკვეთები იტვირთება...',
    'history.empty': 'შეკვეთების ისტორია გამოჩნდება გადახდის შემდეგ.',
    'history.count': '{count} შეკვეთა',
    'history.status': 'სტატუსი',
    'history.delivery': 'მიტანა',
    'history.items': 'ნივთი',
    'history.ordertotal': 'ჯამი',
    'history.for': 'ვის:',
    'history.showdetails': 'დეტალების ნახვა',
    'history.hidedetails': 'დეტალების დამალვა',
    'history.address': 'მიტანის მისამართი',
    'history.paymethod': 'გადახდის მეთოდი',
    'history.note.label': 'შენიშვნა',
    'history.items.title': 'შეძენილი ნივთები',
    'history.total.label': 'შეკვეთის ჯამი',
    'history.filter.showing': 'ნაჩვენებია {count} {total}-დან',
    'history.nomatch': 'ამ ფილტრებით შეკვეთები ვერ მოიძებნა.',
    'history.clearfilters': 'ფილტრების გასუფთავება',
    'history.nofound.title': 'შეკვეთა ჯერ არ გაქვთ',
    'history.nofound.desc': 'შეკვეთის განთავსების შემდეგ ის გამოჩნდება აქ.',
    'history.nofound.btn1': 'თაიგულების დათვალიერება',
    'history.nofound.btn2': 'AI დიზაინი',
    'history.continue': 'შოპინგის გაგრძელება',
    'history.tryai': 'AI დიზაინი',
    'history.saved': 'შენახული',
    'history.demo': 'სადემო',
    'history.source.backend': 'ბაზიდან ჩამოტვირთულია',
    'history.source.merged': 'ბაზა + ლოკალური',
    'history.source.local': 'ლოკალიდან ჩამოტვირთულია',
    // AI Designer
    'ai.title': 'AI თაიგულის დიზაინი',
    'ai.desc': 'შეარჩიეთ სასურველი პარამეტრები და ჩვენი AI შექმნის დიზაინის ვარიანტებს.',
    'ai.form.title': 'შექმენი შენი თაიგული',
    'ai.occasion': 'შემთხვევა',
    'ai.style': 'სტილი',
    'ai.size': 'ზომა',
    'ai.wrap': 'შეფუთვა',
    'ai.flowers': 'სასურველი ყვავილები',
    'ai.flowers.any': '(ნებისმიერი)',
    'ai.colors': 'სასურველი ფერები',
    'ai.colors.any': '(ნებისმიერი)',
    'ai.details': 'დამატებითი დეტალები',
    'ai.details.optional': '(სურვილისამებრ)',
    'ai.details.placeholder': 'მაგ: ბუნებრივი, სოფლის სტილი ზაფხულის ქორწილისთვის...',
    'ai.generate': 'თაიგულის შექმნა',
    'ai.generating': 'იქმნება...',
    'ai.empty': 'შეავსეთ სასურველი პარამეტრები და დააჭირეთ "შექმნა"',
    'ai.loading': 'იქმნება თქვენი ვარიანტები...',
    'ai.fallback': 'ნაჩვენებია სიმულირებული შედეგები (სერვერი მიუწვდომელია).',
    'ai.prompt.label': 'გენერირებული პრომპტი',
    'ai.choose': 'შეარჩიეთ დიზაინი',
    'ai.option': 'ვარიანტი',
    'ai.select': 'ამ დიზაინის შერჩევა',
    'ai.generate.diff': 'სხვა ვარიანტების შექმნა',
    'ai.selected.title': 'თქვენი შერჩეული დიზაინი',
    'ai.custom': 'AI სპეციალური თაიგული',
    'ai.design.label': 'AI დიზაინი',
    'ai.prompt.title': 'თქვენი პრომპტი',
    'ai.occasion.label': 'შემთხვევა',
    'ai.size.label': 'ზომა',
    'ai.addtocart': 'კალათაში დამატება',
    'ai.added': 'კალათაში დაემატა!',
    'ai.again': 'ახლიდან შექმნა',
    'ai.viewcart': 'კალათის ნახვა',
    // AI Designer chip labels
    'ai.occ.Birthday': 'დაბადების დღე',
    'ai.occ.Anniversary': 'იუბილე',
    'ai.occ.Wedding': 'ქორწილი',
    'ai.occ.Romantic Gift': 'რომანტიკული საჩუქარი',
    'ai.occ.Sympathy': 'სამძიმარი',
    'ai.occ.Graduation': 'გამოსაშვები',
    'ai.occ.General Gift': 'საჩუქარი',
    'ai.sty.Romantic': 'რომანტიკული',
    'ai.sty.Minimal': 'მინიმალური',
    'ai.sty.Luxury': 'ლუქსი',
    'ai.sty.Wildflower': 'ველური ყვავილები',
    'ai.sty.Modern': 'თანამედროვე',
    'ai.sty.Classic': 'კლასიკური',
    'ai.sz.Small': 'პატარა',
    'ai.sz.Medium': 'საშუალო',
    'ai.sz.Large': 'დიდი',
    'ai.sz.Extra Large': 'ძალიან დიდი',
    'ai.wrp.Kraft paper': 'კრაფტის ქაღალდი',
    'ai.wrp.Satin ribbon': 'ატლასის ლენტი',
    'ai.wrp.Luxury box': 'ლუქს ყუთი',
    'ai.wrp.Transparent wrap': 'გამჭვირვალე შეფუთვა',
    'ai.wrp.Minimal white wrap': 'მინიმალური თეთრი შეფუთვა',
    'ai.flr.Roses': 'ვარდები',
    'ai.flr.Peonies': 'პეონები',
    'ai.flr.Tulips': 'ტიტები',
    'ai.flr.Sunflowers': 'მზესუმზირები',
    'ai.flr.Lilies': 'შროშანები',
    'ai.flr.Lavender': 'ლავანდა',
    'ai.flr.Orchids': 'ორქიდეები',
    'ai.flr.Dahlias': 'დალიები',
    'ai.flr.Wildflowers': 'ველური ყვავილები',
    'ai.clr.Red': 'წითელი',
    'ai.clr.Pink': 'ვარდისფერი',
    'ai.clr.White': 'თეთრი',
    'ai.clr.Yellow': 'ყვითელი',
    'ai.clr.Orange': 'ნარინჯისფერი',
    'ai.clr.Purple': 'იასამნისფერი',
    'ai.clr.Blue': 'ლურჯი',
    'ai.clr.Peach': 'ატმისფერი',
    'ai.clr.Coral': 'კოალი',
    'ai.clr.Lavender': 'ლავანდისფერი',
    // Contact
    'contact.title': 'კონტაქტი',
    'contact.subtitle': 'გაქვთ კითხვა ან შეფასება? სიხარულით გამოვეხმაურებით.',
    'contact.name': 'სახელი',
    'contact.email': 'ელ-ფოსტა',
    'contact.message': 'შეტყობინება',
    'contact.send': 'გაგზავნა',
    'contact.sending': 'იგზავნება...',
    'contact.success.title': 'შეტყობინება მიღებულია!',
    'contact.success.desc': 'გმადლობთ, {name}. თქვენი შეტყობინება მიღებულია და მალე გამოვეხმაურებით.',
    'contact.success.backend': 'შეტყობინება ბაზაში შენახულია.',
    'contact.success.local': 'შეტყობინება ლოკალურად შენახულია.',
    'contact.success.another': 'კიდევ ერთი შეტყობინება',
    'err.name.contact': 'სახელი სავალდებულოა.',
    'err.email.required': 'ელ-ფოსტა სავალდებულოა.',
    'err.email.invalid': 'გთხოვთ, შეიყვანოთ სწორი ელ-ფოსტა.',
    'err.message': 'შეტყობინება სავალდებულოა.',
    // About
    'about.title': 'FloraDesigner-ის შესახებ',
    'about.desc': 'FloraDesigner არის სრული სტეკის AI-ასისტირებული ყვავილების მარკეტპლეისი, შექმნილი სამაგისტრო კვლევის პროექტად. ის წარმოაჩენს სრულ ელ-კომერციის ნაკადს – დათვალიერებიდან AI-ის მიერ შექმნილ დიზაინამდე, კალათიდან გადახდამდე, შეკვეთების ისტორიამდე და ადმინ მართვამდე – React, Node.js, Express, MongoDB და Tailwind CSS-ის გამოყენებით.',
    'about.features': 'ფუნქციები',
    'about.f1.title': 'მზა თაიგულების მაღაზია',
    'about.f1.desc': 'გადახედეთ კატეგორიის, ფერის, ყვავილის სახეობის, ზომის, შემთხვევისა და ფასის ფილტრებით.',
    'about.f2.title': 'AI თაიგულის დიზაინი (სიმულირებული)',
    'about.f2.desc': 'აღწერეთ სურვილი – შემთხვევა, ყვავილები, ფერები, სტილი – და სისტემა შექმნის კონცეფციას ფასის შეფასებით.',
    'about.f3.title': 'კალათა და გადახდა',
    'about.f3.desc': 'ჩამატეთ ნივთები, გადახედეთ შეკვეთას, შეიყვანეთ მიტანის დეტალები და შეარჩიეთ გადახდის მეთოდი.',
    'about.f4.title': 'შეკვეთების ისტორია',
    'about.f4.desc': 'ყველა შეკვეთა ინახება სტატუსის ბეჯებით, ტიპის ფილტრებით და გამფართოებელი პანელებით.',
    'about.f5.title': 'ადმინ პანელი',
    'about.f5.desc': 'სადემო ადმინ პანელი შეკვეთებისა და პროდუქტების სამართავად.',
    'about.techstack': 'ტექნოლოგიები',
    'about.note': 'AI ყვავილის გენერაცია სიმულირებულია – მესამე მხარის AI API არ გამოიყენება. გადახდა სადემოა და რეალური ტრანზაქციები არ ხდება.',
  },
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.ai': 'AI Designer',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.orders': 'My Orders',
    'nav.cart': 'Cart',
    // Common filter values
    'All': 'All',
    'In Stock': 'In Stock',
    'Unavailable': 'Unavailable',
    'Out of Stock': 'Out of Stock',
    'Any Price': 'Any Price',
    'Under ₾80': 'Under ₾80',
    '₾80 - ₾120': '₾80 - ₾120',
    '₾120 - ₾160': '₾120 - ₾160',
    'Over ₾160': 'Over ₾160',
    // Order type / status labels
    'Ready-made': 'Ready-made',
    'AI-generated': 'AI-generated',
    'Mixed': 'Mixed',
    'Pending': 'Pending',
    'Preparing': 'Preparing',
    'Out for Delivery': 'Out for Delivery',
    'Delivered': 'Delivered',
    'Cancelled': 'Cancelled',
    // Payment labels
    'pay.cash': 'Cash on Delivery',
    'pay.cash.desc': 'Pay when your bouquet arrives at your door.',
    'pay.card': 'Demo Card Payment',
    'pay.card.desc': 'Simulated card payment - no real transaction occurs.',
    'pay.bank': 'Bank Transfer Simulation',
    'pay.bank.desc': 'Simulated bank transfer confirmation for demo purposes.',
    // Home
    'home.tag': 'Fresh · Handcrafted · AI-Powered',
    'home.title1': 'Beautiful Bouquets,',
    'home.title2': 'Designed for You',
    'home.desc': 'Browse our handcrafted collection or let AI create a custom bouquet perfectly tailored to your vision, occasion, and taste.',
    'home.browse': 'Browse Bouquets',
    'home.tryai': 'Try AI Designer',
    'home.featured': 'Featured Arrangements',
    'home.viewall': 'View all bouquets →',
    'home.how.title': 'How AI Bouquet Design Works',
    'home.how.desc': 'Creating a custom bouquet has never been easier. Just describe what you want and our AI handles the rest.',
    'home.step1.title': 'Describe Your Vision',
    'home.step1.desc': 'Tell us the occasion, your favorite colors, preferred flowers, and any special requests in natural language.',
    'home.step2.title': 'AI Designs Your Bouquet',
    'home.step2.desc': 'Our AI instantly generates a custom bouquet tailored to your description, style preferences, and budget.',
    'home.step3.title': 'Review and Customize',
    'home.step3.desc': 'Browse the AI suggestions, adjust details, swap flowers, or pick a similar style from our curated catalog.',
    'home.step4.title': 'Order and Receive Fresh',
    'home.step4.desc': 'Place your order and receive hand-assembled, fresh-cut flowers delivered right to your door.',
    'home.why.title': 'Why FloraDesigner?',
    'home.why.desc': 'We combine the warmth of artisan floristry with the precision of modern technology.',
    'home.ben1.title': 'Expert Curation',
    'home.ben1.desc': 'Every bouquet in our catalog is hand-selected by professional florists who care about quality and beauty.',
    'home.ben2.title': 'Fresh Daily Delivery',
    'home.ben2.desc': 'We source directly from local growers to ensure your flowers arrive at peak freshness, never from cold storage.',
    'home.ben3.title': 'AI-Powered Customization',
    'home.ben3.desc': 'Not finding exactly what you want? Let AI design a one-of-a-kind bouquet based on your vision.',
    'home.ben4.title': '100% Satisfaction',
    'home.ben4.desc': 'If your bouquet does not meet expectations, we will replace it or refund your order - no questions asked.',
    'home.cta.title': 'Ready to Find Your Perfect Bouquet?',
    'home.cta.desc': 'Browse a curated selection of handcrafted arrangements or describe your dream bouquet to our AI designer.',
    'home.cta.shop': 'Shop Now',
    'home.cta.ai': 'AI Designer',
    // Products
    'products.title': 'Our Bouquets',
    'products.subtitle': 'Browse our full collection of handcrafted floral arrangements.',
    'products.fallback': 'Using demo product data because the backend is unavailable.',
    'products.search': 'Search bouquets by name or description...',
    'products.filter.category': 'Category',
    'products.filter.color': 'Color',
    'products.filter.flower': 'Flower Type',
    'products.filter.size': 'Size',
    'products.filter.occasion': 'Occasion',
    'products.filter.price': 'Price Range',
    'products.instock.label': 'In-stock only',
    'products.clearall': 'Clear all filters',
    'products.loading': 'Loading bouquets...',
    'products.showing': 'Showing {count} of {total} bouquets',
    'products.nomatch': 'No bouquets match your filters.',
    'products.clearfilters': 'Clear filters',
    'products.viewdetails': 'View Details',
    'products.addtocart': 'Add to Cart',
    'products.added': 'Added!',
    // ProductDetails
    'details.back': '← Back to bouquets',
    'details.loading': 'Loading bouquet...',
    'details.notfound.title': 'Bouquet Not Found',
    'details.notfound.desc': 'We could not find a bouquet with that ID. It may have been removed or the link may be wrong.',
    'details.notfound.btn': 'Back to All Bouquets',
    'details.flowers': 'Flowers',
    'details.colors': 'Colors',
    'details.size': 'Size',
    'details.occasion': 'Occasion',
    'details.availability': 'Availability',
    'details.delivery': 'Delivery',
    'details.instock': 'In Stock',
    'details.outofstock': 'Currently Unavailable',
    'details.arrangement': 'arrangement',
    'details.idealfor': 'Ideal for',
    'details.qty': 'Quantity:',
    'details.addtocart': 'Add to Cart',
    'details.added': 'Added to cart! —',
    'details.viewcart': 'View Cart',
    'details.addedlabel': 'Added to Cart!',
    'details.outofstock.msg': 'This bouquet is currently out of stock. Check back soon or browse similar arrangements.',
    'details.related': 'You might also like',
    // Cart
    'cart.title': 'Your Cart',
    'cart.empty.text': 'Your cart is empty.',
    'cart.empty.btn': 'Browse Bouquets',
    'cart.clear': 'Clear Cart',
    'cart.summary': 'Order Summary',
    'cart.total': 'Total',
    'cart.shipping': 'Shipping calculated at checkout',
    'cart.checkout': 'Proceed to Checkout',
    'cart.continueshop': 'Continue Shopping',
    'cart.each': 'each',
    'cart.item.ai': 'AI-generated',
    'cart.item.ready': 'Ready-made',
    'cart.item.custom': 'Custom',
    // Checkout
    'checkout.title': 'Checkout',
    'checkout.subtitle': 'Complete your delivery details to place your order.',
    'checkout.empty.text': 'Your cart is empty. Add some bouquets before checking out.',
    'checkout.empty.btn': 'Browse Bouquets',
    'checkout.delivery.title': 'Delivery Details',
    'checkout.name': 'Full Name',
    'checkout.phone': 'Phone Number',
    'checkout.address': 'Delivery Address',
    'checkout.date': 'Delivery Date',
    'checkout.timeslot': 'Time Slot',
    'checkout.note': 'Note for Florist',
    'checkout.note.optional': '(optional)',
    'checkout.note.placeholder': 'Card message, special requests, access instructions...',
    'checkout.payment.title': 'Payment Method',
    'checkout.payment.note': 'This is a demo store - no real payments are processed.',
    'checkout.submit': 'Place Order',
    'checkout.placing': 'Placing Order...',
    'checkout.back': 'Back to Cart',
    'checkout.summary': 'Order Summary',
    'checkout.qty': 'Qty:',
    'checkout.subtotal': 'Subtotal',
    'checkout.delivery.free': 'Delivery',
    'checkout.free': 'Free',
    'checkout.total': 'Total',
    'checkout.time.select': 'Select a time slot',
    'err.name': 'Full name is required.',
    'err.phone': 'Phone number is required.',
    'err.address': 'Delivery address is required.',
    'err.date': 'Delivery date is required.',
    'err.time': 'Please select a delivery time slot.',
    'err.payment': 'Please select a payment method.',
    // OrderSuccess
    'success.nofound.text': 'No recent order found. Start shopping to place your first order.',
    'success.nofound.btn1': 'Browse Bouquets',
    'success.nofound.btn2': 'Back to Home',
    'success.title': 'Order Placed!',
    'success.desc': 'Thank you, {name}. Your bouquet order has been received and will be prepared for delivery.',
    'success.backend': 'Order saved to backend database.',
    'success.local': 'Demo order saved locally because the backend was unavailable.',
    'success.details': 'Order Details',
    'success.orderid': 'Order ID',
    'success.customer': 'Customer',
    'success.phone': 'Phone',
    'success.deliveryto': 'Delivery To',
    'success.deliverydate': 'Delivery Date',
    'success.timeslot': 'Time Slot',
    'success.payment': 'Payment',
    'success.note': 'Note',
    'success.items': 'Items Ordered',
    'success.total': 'Total',
    'success.continue': 'Continue Shopping',
    'success.vieworders': 'View My Orders',
    // OrderHistory
    'history.title': 'My Orders',
    'history.loading': 'Loading your orders...',
    'history.empty': 'Your order history will appear here after you check out.',
    'history.count': '{count} order{plural}',
    'history.status': 'Status',
    'history.delivery': 'Delivery',
    'history.items': 'item{plural}',
    'history.ordertotal': 'Order Total',
    'history.for': 'For',
    'history.showdetails': 'View details',
    'history.hidedetails': 'Hide details',
    'history.address': 'Delivery Address',
    'history.paymethod': 'Payment Method',
    'history.note.label': 'Note',
    'history.items.title': 'Items Ordered',
    'history.total.label': 'Order Total',
    'history.filter.showing': 'Showing {count} of {total} order{plural}',
    'history.nomatch': 'No orders match these filters.',
    'history.clearfilters': 'Clear filters',
    'history.nofound.title': 'No orders yet',
    'history.nofound.desc': 'When you place an order it will appear here.',
    'history.nofound.btn1': 'Browse Bouquets',
    'history.nofound.btn2': 'Try AI Designer',
    'history.continue': 'Continue Shopping',
    'history.tryai': 'Try AI Designer',
    'history.saved': 'Saved',
    'history.demo': 'Demo',
    'history.source.backend': 'Loaded from database',
    'history.source.merged': 'Database + local fallback',
    'history.source.local': 'Loaded locally',
    // AI Designer
    'ai.title': 'AI Bouquet Designer',
    'ai.desc': 'Choose your preferences and our AI will generate unique bouquet design options for you.',
    'ai.form.title': 'Design Your Bouquet',
    'ai.occasion': 'Occasion',
    'ai.style': 'Style',
    'ai.size': 'Bouquet Size',
    'ai.wrap': 'Wrapping Style',
    'ai.flowers': 'Preferred Flowers',
    'ai.flowers.any': '(choose any)',
    'ai.colors': 'Preferred Colors',
    'ai.colors.any': '(choose any)',
    'ai.details': 'Additional Details',
    'ai.details.optional': '(optional)',
    'ai.details.placeholder': 'e.g. Garden-fresh with a rustic feel for an outdoor June wedding...',
    'ai.generate': 'Generate Bouquet Designs',
    'ai.generating': 'Generating designs...',
    'ai.empty': 'Fill in your preferences and click Generate',
    'ai.loading': 'Designing your bouquet options...',
    'ai.fallback': 'Showing simulated results because the backend is unavailable.',
    'ai.prompt.label': 'Generated prompt',
    'ai.choose': 'Choose Your Design',
    'ai.option': 'Option',
    'ai.select': 'Select This Design',
    'ai.generate.diff': 'Generate different options',
    'ai.selected.title': 'Your Selected Design',
    'ai.custom': 'Custom AI Bouquet',
    'ai.design.label': 'AI Design',
    'ai.prompt.title': 'Your prompt',
    'ai.occasion.label': 'Occasion',
    'ai.size.label': 'Size',
    'ai.addtocart': 'Add to Cart',
    'ai.added': 'Added to cart!',
    'ai.again': 'Design Again',
    'ai.viewcart': 'View Cart',
    // AI Designer chip labels
    'ai.occ.Birthday': 'Birthday',
    'ai.occ.Anniversary': 'Anniversary',
    'ai.occ.Wedding': 'Wedding',
    'ai.occ.Romantic Gift': 'Romantic Gift',
    'ai.occ.Sympathy': 'Sympathy',
    'ai.occ.Graduation': 'Graduation',
    'ai.occ.General Gift': 'General Gift',
    'ai.sty.Romantic': 'Romantic',
    'ai.sty.Minimal': 'Minimal',
    'ai.sty.Luxury': 'Luxury',
    'ai.sty.Wildflower': 'Wildflower',
    'ai.sty.Modern': 'Modern',
    'ai.sty.Classic': 'Classic',
    'ai.sz.Small': 'Small',
    'ai.sz.Medium': 'Medium',
    'ai.sz.Large': 'Large',
    'ai.sz.Extra Large': 'Extra Large',
    'ai.wrp.Kraft paper': 'Kraft paper',
    'ai.wrp.Satin ribbon': 'Satin ribbon',
    'ai.wrp.Luxury box': 'Luxury box',
    'ai.wrp.Transparent wrap': 'Transparent wrap',
    'ai.wrp.Minimal white wrap': 'Minimal white wrap',
    'ai.flr.Roses': 'Roses',
    'ai.flr.Peonies': 'Peonies',
    'ai.flr.Tulips': 'Tulips',
    'ai.flr.Sunflowers': 'Sunflowers',
    'ai.flr.Lilies': 'Lilies',
    'ai.flr.Lavender': 'Lavender',
    'ai.flr.Orchids': 'Orchids',
    'ai.flr.Dahlias': 'Dahlias',
    'ai.flr.Wildflowers': 'Wildflowers',
    'ai.clr.Red': 'Red',
    'ai.clr.Pink': 'Pink',
    'ai.clr.White': 'White',
    'ai.clr.Yellow': 'Yellow',
    'ai.clr.Orange': 'Orange',
    'ai.clr.Purple': 'Purple',
    'ai.clr.Blue': 'Blue',
    'ai.clr.Peach': 'Peach',
    'ai.clr.Coral': 'Coral',
    'ai.clr.Lavender': 'Lavender',
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have a question or feedback? We would love to hear from you.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success.title': 'Message Received!',
    'contact.success.desc': 'Thank you, {name}. We have received your message and will get back to you shortly.',
    'contact.success.backend': 'Message saved to database.',
    'contact.success.local': 'Message saved locally.',
    'contact.success.another': 'Send Another Message',
    'err.name.contact': 'Name is required.',
    'err.email.required': 'Email is required.',
    'err.email.invalid': 'Please enter a valid email address.',
    'err.message': 'Message is required.',
    // About
    'about.title': 'About FloraDesigner',
    'about.desc': 'FloraDesigner is a full-stack AI-assisted bouquet marketplace built as a bachelor graduation project. It demonstrates a complete e-commerce flow - from browsing and AI-assisted design to cart, checkout, order history, and admin management - using React, Node.js, Express, MongoDB, and Tailwind CSS.',
    'about.features': 'Features',
    'about.f1.title': 'Ready-Made Bouquet Shop',
    'about.f1.desc': 'Browse a curated catalog of handcrafted arrangements, filterable by category, color, flower type, size, occasion, and price range.',
    'about.f2.title': 'AI Bouquet Designer (Simulated)',
    'about.f2.desc': 'Describe your vision - occasion, preferred flowers, colors, and style - and the system generates a custom bouquet concept complete with a price estimate.',
    'about.f3.title': 'Cart and Checkout',
    'about.f3.desc': 'Add items to cart, review the order, enter delivery details, and choose a simulated payment method. No real transactions are processed.',
    'about.f4.title': 'Order History',
    'about.f4.desc': 'All placed orders are tracked in the browser with status badges, type filters (Ready-made, AI-generated, Mixed), and expandable detail panels.',
    'about.f5.title': 'Admin Dashboard',
    'about.f5.desc': 'Demo admin dashboard for viewing and managing orders (update statuses) and maintaining the product catalog (add, edit, delete bouquets).',
    'about.techstack': 'Tech Stack',
    'about.note': 'AI bouquet generation is simulated - no third-party AI image API is used. Payment processing is for demonstration only and no real transactions occur.',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const stored = localStorage.getItem(LS_KEY);
      return stored === 'en' ? 'en' : 'ka';
    } catch {
      return 'ka';
    }
  });

  const setLanguage = useCallback((lang) => {
    setLanguageState(lang);
    try { localStorage.setItem(LS_KEY, lang); } catch {}
  }, []);

  const t = useCallback((key, vars = {}) => {
    let str = translations[language]?.[key] ?? translations['en']?.[key] ?? key;
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(`{${k}}`, String(v));
    });
    return str;
  }, [language]);

  const formatCurrency = useCallback((amount) => {
    const num = Math.round(Number(amount) || 0);
    return language === 'ka' ? `₾${num}` : `${num} GEL`;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
